// Auto-generated by scripts/generate-no-italics-override.mjs from
// scripts/templates/no-italics-extension.template.js - edit the template, not the output.
'use strict'

const vscode = require('vscode')
const forge = require('./forge')

const SETTING_ID = "hearthcode.disableItalics"
const THEME_KEY = "[HearthCode Moss Dark][HearthCode Moss Light][HearthCode Ember Dark][HearthCode Ember Light]"
const OVERRIDE_BY_EDITOR_KEY = {
  "tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "HearthCode italics off",
        "scope": [
          "comment",
          "punctuation.definition.comment",
          "entity.name.type",
          "entity.name.class",
          "storage.type.java",
          "storage.type.primitive.java",
          "entity.name.struct.rust",
          "entity.name.type.class",
          "support.type",
          "support.type.builtin",
          "support.class",
          "meta.decorator",
          "punctuation.decorator",
          "markup.italic"
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  },
  "semanticTokenColorCustomizations": {
    "enabled": true,
    "rules": {
      "class": {
        "italic": false
      },
      "interface": {
        "italic": false
      },
      "type": {
        "italic": false
      },
      "type.defaultLibrary": {
        "italic": false
      },
      "typeParameter": {
        "italic": false
      },
      "enum": {
        "italic": false
      },
      "decorator": {
        "italic": false
      }
    }
  }
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

async function syncOverride(enabled) {
  const editorConfig = vscode.workspace.getConfiguration('editor')
  for (const [editorKey, themeBlock] of Object.entries(OVERRIDE_BY_EDITOR_KEY)) {
    const inspected = editorConfig.inspect(editorKey)
    const globalValue = inspected && isPlainObject(inspected.globalValue) ? inspected.globalValue : {}
    const desiredBlock = enabled ? themeBlock : undefined
    if (JSON.stringify(globalValue[THEME_KEY]) === JSON.stringify(desiredBlock)) continue
    const next = { ...globalValue }
    if (enabled) {
      next[THEME_KEY] = themeBlock
    } else {
      delete next[THEME_KEY]
    }
    const value = Object.keys(next).length > 0 ? next : undefined
    await editorConfig.update(editorKey, value, vscode.ConfigurationTarget.Global)
  }
}

function isEnabled() {
  return vscode.workspace.getConfiguration().get(SETTING_ID) === true
}

function activate(context) {
  // On startup, refresh the override only when the toggle is on, so the rules
  // baked into this build stay current across extension updates. When the
  // toggle is off, user settings are left alone: an override pasted manually
  // from the docs must survive activation.
  if (isEnabled()) {
    void syncOverride(true)
  }
  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration((event) => {
      if (!event.affectsConfiguration(SETTING_ID)) return
      void syncOverride(isEnabled())
    })
  )
  forge.activate(context, vscode)
}

function deactivate() {
  forge.deactivate?.()
}

module.exports = { activate, deactivate }
