import { hexToRgba, normalizeHex, rgbaToHex } from '../../color-utils.mjs'

const VARIANT_ORDER = ['dark', 'light']

const ANSI_SLOTS = [
  ['black', 'terminalBlack'],
  ['red', 'terminalRed'],
  ['green', 'terminalGreen'],
  ['yellow', 'terminalYellow'],
  ['blue', 'terminalBlue'],
  ['magenta', 'terminalMagenta'],
  ['cyan', 'terminalCyan'],
  ['white', 'terminalWhite'],
  ['brightBlack', 'terminalBrightBlack'],
  ['brightRed', 'terminalBrightRed'],
  ['brightGreen', 'terminalBrightGreen'],
  ['brightYellow', 'terminalBrightYellow'],
  ['brightBlue', 'terminalBrightBlue'],
  ['brightMagenta', 'terminalBrightMagenta'],
  ['brightCyan', 'terminalBrightCyan'],
  ['brightWhite', 'terminalBrightWhite'],
]

function requireHex(tokens, key, label) {
  const value = normalizeHex(tokens?.[key])
  if (!value) {
    throw new Error(`terminal emitter: ${label} is missing valid token "${key}"`)
  }
  return value
}

export function compositeOpaque(foregroundHex, backgroundHex) {
  const foreground = hexToRgba(foregroundHex)
  const background = hexToRgba(backgroundHex)
  if (!foreground || !background) {
    throw new Error(`terminal emitter: cannot composite "${foregroundHex}" over "${backgroundHex}"`)
  }

  if (!foreground.hasAlpha || foreground.a === 255) {
    return rgbaToHex({ ...foreground, a: 255, hasAlpha: false })
  }

  const alpha = foreground.a / 255
  return rgbaToHex({
    r: foreground.r * alpha + background.r * (1 - alpha),
    g: foreground.g * alpha + background.g * (1 - alpha),
    b: foreground.b * alpha + background.b * (1 - alpha),
    a: 255,
    hasAlpha: false,
  })
}

function buildTerminalTheme({ schemeId, schemeName, variantId, tokens }) {
  const label = `HearthCode ${schemeName} ${variantId === 'dark' ? 'Dark' : 'Light'}`
  const background = requireHex(tokens, 'bg', label)
  const foreground = requireHex(tokens, 'fg', label)
  const cursor = compositeOpaque(requireHex(tokens, 'cursor', label), background)
  const selection = compositeOpaque(requireHex(tokens, 'selection', label), background)
  const ansi = Object.fromEntries(
    ANSI_SLOTS.map(([slot, token]) => [slot, compositeOpaque(requireHex(tokens, token, label), background)]),
  )

  return {
    schemeId,
    schemeName,
    variantId,
    label,
    slug: `hearthcode-${schemeId}-${variantId}`,
    background: compositeOpaque(background, background),
    foreground: compositeOpaque(foreground, background),
    cursor,
    cursorText: compositeOpaque(background, background),
    selection,
    selectionText: compositeOpaque(foreground, background),
    ansi,
  }
}

function quoteYaml(value) {
  return `"${String(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`
}

function renderWarp(theme) {
  const normal = ANSI_SLOTS.slice(0, 8)
  const bright = ANSI_SLOTS.slice(8)
  const lines = [
    '# Auto-generated by scripts/sync-themes.mjs. Do not edit.',
    `accent: ${quoteYaml(theme.cursor)}`,
    `background: ${quoteYaml(theme.background)}`,
    `details: ${theme.variantId === 'dark' ? 'darker' : 'lighter'}`,
    `foreground: ${quoteYaml(theme.foreground)}`,
    'terminal_colors:',
    '  bright:',
    ...bright.map(([slot], index) => `    ${normal[index][0]}: ${quoteYaml(theme.ansi[slot])}`),
    '  normal:',
    ...normal.map(([slot]) => `    ${slot}: ${quoteYaml(theme.ansi[slot])}`),
    '',
  ]
  return lines.join('\n')
}

function renderKitty(theme) {
  const lines = [
    '# Auto-generated by scripts/sync-themes.mjs. Do not edit.',
    `# ${theme.label}`,
    '',
    `background ${theme.background}`,
    `foreground ${theme.foreground}`,
    `cursor ${theme.cursor}`,
    `cursor_text_color ${theme.cursorText}`,
    `selection_background ${theme.selection}`,
    `selection_foreground ${theme.selectionText}`,
    '',
    ...ANSI_SLOTS.map(([slot], index) => `color${index} ${theme.ansi[slot]}`),
    '',
  ]
  return lines.join('\n')
}

function renderAlacritty(theme) {
  const normal = ANSI_SLOTS.slice(0, 8)
  const bright = ANSI_SLOTS.slice(8)
  const lines = [
    '# Auto-generated by scripts/sync-themes.mjs. Do not edit.',
    `# ${theme.label}`,
    '',
    '[colors.primary]',
    `background = '${theme.background}'`,
    `foreground = '${theme.foreground}'`,
    '',
    '[colors.cursor]',
    `cursor = '${theme.cursor}'`,
    `text = '${theme.cursorText}'`,
    '',
    '[colors.selection]',
    `background = '${theme.selection}'`,
    `text = '${theme.selectionText}'`,
    '',
    '[colors.normal]',
    ...normal.map(([slot]) => `${slot.padEnd(7)} = '${theme.ansi[slot]}'`),
    '',
    '[colors.bright]',
    ...bright.map(([slot], index) => `${normal[index][0].padEnd(7)} = '${theme.ansi[slot]}'`),
    '',
  ]
  return lines.join('\n')
}

function windowsScheme(theme) {
  return {
    name: theme.label,
    background: theme.background,
    foreground: theme.foreground,
    cursorColor: theme.cursor,
    selectionBackground: theme.selection,
    ...Object.fromEntries(ANSI_SLOTS.map(([slot]) => [slot, theme.ansi[slot]])),
  }
}

function renderWindowsTerminal(themes) {
  return `${JSON.stringify({
    $schema: 'https://aka.ms/terminal-profiles-schema',
    schemes: themes.map(windowsScheme),
  }, null, 2)}\n`
}

function xmlEscape(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

function component(value) {
  const normalized = (value / 255).toFixed(10).replace(/0+$/, '').replace(/\.$/, '')
  return normalized || '0'
}

function iTermColorEntry(name, hex) {
  const color = hexToRgba(hex)
  if (!color) throw new Error(`terminal emitter: invalid iTerm2 color "${hex}"`)
  return [
    `  <key>${xmlEscape(name)}</key>`,
    '  <dict>',
    `    <key>Blue Component</key><real>${component(color.b)}</real>`,
    '    <key>Color Space</key><string>sRGB</string>',
    `    <key>Green Component</key><real>${component(color.g)}</real>`,
    `    <key>Red Component</key><real>${component(color.r)}</real>`,
    '  </dict>',
  ].join('\n')
}

function renderITerm2(theme) {
  const entries = [
    ...ANSI_SLOTS.map(([slot], index) => [`Ansi ${index} Color`, theme.ansi[slot]]),
    ['Background Color', theme.background],
    ['Bold Color', theme.ansi.brightWhite],
    ['Cursor Color', theme.cursor],
    ['Cursor Text Color', theme.cursorText],
    ['Foreground Color', theme.foreground],
    ['Selected Text Color', theme.selectionText],
    ['Selection Color', theme.selection],
  ]

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<!-- Auto-generated by scripts/sync-themes.mjs. Do not edit. -->',
    '<plist version="1.0">',
    '<dict>',
    ...entries.map(([name, color]) => iTermColorEntry(name, color)),
    '</dict>',
    '</plist>',
    '',
  ].join('\n')
}

export function renderTerminalFiles({ schemeId, schemeName, tokenSets }) {
  const themes = VARIANT_ORDER
    .filter((variantId) => tokenSets?.[variantId])
    .map((variantId) => buildTerminalTheme({
      schemeId,
      schemeName,
      variantId,
      tokens: tokenSets[variantId],
    }))

  if (themes.length === 0) {
    throw new Error(`terminal emitter: no token sets available for scheme "${schemeId}"`)
  }

  const files = []
  for (const theme of themes) {
    const warpSlug = theme.slug.replaceAll('-', '_')
    files.push(
      { path: `terminal/warp/${warpSlug}.yaml`, content: renderWarp(theme) },
      { path: `terminal/kitty/${theme.slug}.conf`, content: renderKitty(theme) },
      { path: `terminal/alacritty/${theme.slug}.toml`, content: renderAlacritty(theme) },
      { path: `terminal/iterm2/${theme.slug}.itermcolors`, content: renderITerm2(theme) },
    )
  }

  files.push({
    path: `terminal/windows-terminal/hearthcode-${schemeId}.json`,
    content: renderWindowsTerminal(themes),
  })
  return files
}

export { ANSI_SLOTS }
