// The web platform emitter — one concrete implementation of the `Emitter`
// contract (scripts/theme-engine/types.mjs).
//
// Phase 5 of the extraction plan: establishes the platform-plugin boundary with a
// REAL, byte-exact emitter. It reproduces what scripts/sync-themes.mjs writes to
// src/data/tokens.ts from the resolved platform-token maps, now behind the
// {name, consumes, emit} interface. Additive — sync-themes still owns the write;
// this proves an emitter is a pure (ir) -> File[] function.
//
// The richer vscode / obsidian emitters (whose write-side is spread across the
// generate-*.mjs scripts) are the follow-up; web is the cleanest first one.

import { getExportedSiteTokenKeys } from '../../color-system/build.mjs'

const EXPORTED_SITE_TOKEN_KEYS = getExportedSiteTokenKeys()

/** @type {import('../types.mjs').Emitter} */
export const webEmitter = {
  name: 'web',
  // Reads the resolved `web` platform-token map (itself derived from every layer).
  // A finer layer-level contract is a follow-up.
  consumes: ['web'],

  // `maps` is the output of buildGeneratedPlatformTokenMaps(model).
  emit(maps) {
    const tokens = Object.fromEntries(
      Object.entries(maps.web).map(([variantId, tokenSet]) => [
        variantId,
        Object.fromEntries(EXPORTED_SITE_TOKEN_KEYS.map((key) => [key, tokenSet[key]])),
      ]),
    )
    // Header preserved verbatim so the output stays byte-identical to the file
    // sync-themes currently writes.
    const content =
      `// Auto-generated by scripts/sync-themes.mjs - DO NOT EDIT\n` +
      `export const tokens = ${JSON.stringify(tokens, null, 2)} as const\n` +
      `export type TokenSet = typeof tokens.dark\n`
    return [{ path: 'src/data/tokens.ts', content }]
  },
}
