import { existsSync, readFileSync } from 'fs'
import { getObsidianThemeOutputFiles, loadColorSystemVariants } from './color-system.mjs'

const OBSIDIAN_THEME_FILES = getObsidianThemeOutputFiles()
const SNIPPET_FILES = loadColorSystemVariants().variants.map((variant) => ({
  id: variant.id,
  path: OBSIDIAN_THEME_FILES[variant.id],
  modeClass: variant.type === 'dark' ? '.theme-dark' : '.theme-light',
}))

const APP_THEME = {
  manifest: 'obsidian/app-theme/manifest.json',
  themeCss: 'obsidian/app-theme/theme.css',
  versions: 'obsidian/app-theme/versions.json',
  screenshot: 'obsidian/app-theme/screenshot.png',
  submissionTemplate: 'obsidian/app-theme/community-css-theme-entry.json',
}

const REQUIRED_SNIPPET_VARS = [
  '--background-primary',
  '--background-secondary',
  '--text-normal',
  '--text-muted',
  '--text-accent',
  '--code-keyword',
  '--code-function',
  '--code-string',
  '--code-value',
  '--code-comment',
]

const REQUIRED_MANIFEST_FIELDS = ['name', 'version', 'minAppVersion', 'author']

const issues = []

function addIssue(message) {
  issues.push(message)
}

function isSemver(value) {
  return /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(String(value || '').trim())
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'))
  } catch (error) {
    addIssue(`${path}: invalid JSON (${error.message})`)
    return null
  }
}

function validateSnippetFiles() {
  const headerToken = 'Auto-generated by scripts/generate-obsidian-themes.mjs'

  for (const file of SNIPPET_FILES) {
    if (!existsSync(file.path)) {
      addIssue(`${file.path}: file not found`)
      continue
    }

    const text = readFileSync(file.path, 'utf8').replace(/\r\n/g, '\n')

    if (!text.includes(headerToken)) {
      addIssue(`${file.path}: missing auto-generated header`)
    }

    if (!text.includes(`${file.modeClass} {`)) {
      addIssue(`${file.path}: missing root selector ${file.modeClass} {`)
    }

    for (const variable of REQUIRED_SNIPPET_VARS) {
      if (!text.includes(`${variable}:`)) {
        addIssue(`${file.path}: missing required var ${variable}`)
      }
    }

    if (!text.includes('.markdown-source-view.mod-cm6')) {
      addIssue(`${file.path}: missing editor syntax selectors`)
    }

    if (!text.includes('.markdown-preview-view pre code')) {
      addIssue(`${file.path}: missing preview syntax selectors`)
    }
  }
}

function validateAppThemeFiles() {
  const manifest = readJson(APP_THEME.manifest)
  if (manifest) {
    for (const field of REQUIRED_MANIFEST_FIELDS) {
      if (!manifest[field] || String(manifest[field]).trim().length === 0) {
        addIssue(`${APP_THEME.manifest}: missing required field \"${field}\"`)
      }
    }

    if (manifest.version && !isSemver(manifest.version)) {
      addIssue(`${APP_THEME.manifest}: version must be semver, got ${manifest.version}`)
    }
    if (manifest.minAppVersion && !isSemver(manifest.minAppVersion)) {
      addIssue(`${APP_THEME.manifest}: minAppVersion must be semver, got ${manifest.minAppVersion}`)
    }

    const versions = readJson(APP_THEME.versions)
    if (versions) {
      const requiredVersion = String(manifest.version || '').trim()
      const requiredMinAppVersion = String(manifest.minAppVersion || '').trim()

      if (!versions[requiredVersion]) {
        addIssue(`${APP_THEME.versions}: missing compatibility entry for ${requiredVersion}`)
      } else if (String(versions[requiredVersion]).trim() !== requiredMinAppVersion) {
        addIssue(
          `${APP_THEME.versions}: ${requiredVersion} should map to ${requiredMinAppVersion}, got ${versions[requiredVersion]}`
        )
      }
    }
  }

  if (!existsSync(APP_THEME.themeCss)) {
    addIssue(`${APP_THEME.themeCss}: file not found`)
  } else {
    const css = readFileSync(APP_THEME.themeCss, 'utf8').replace(/\r\n/g, '\n')

    if (!css.includes('Auto-generated by scripts/generate-obsidian-app-theme.mjs')) {
      addIssue(`${APP_THEME.themeCss}: missing auto-generated header`)
    }

    if (!css.includes('.theme-dark {')) {
      addIssue(`${APP_THEME.themeCss}: missing .theme-dark rules`)
    }

    if (!css.includes('.theme-light {')) {
      addIssue(`${APP_THEME.themeCss}: missing .theme-light rules`)
    }

    if (!css.includes('--code-keyword:')) {
      addIssue(`${APP_THEME.themeCss}: missing syntax variable mappings`)
    }
  }

  if (!existsSync(APP_THEME.submissionTemplate)) {
    addIssue(`${APP_THEME.submissionTemplate}: file not found`)
  } else {
    const template = readJson(APP_THEME.submissionTemplate)
    if (template) {
      if (!template.repo || !String(template.repo).includes('/')) {
        addIssue(`${APP_THEME.submissionTemplate}: repo must be in owner/name format`)
      }
      const modes = Array.isArray(template.modes) ? template.modes : []
      if (!(modes.includes('dark') && modes.includes('light'))) {
        addIssue(`${APP_THEME.submissionTemplate}: modes must include both dark and light`)
      }
      if (!template.screenshot) {
        addIssue(`${APP_THEME.submissionTemplate}: screenshot field is required`)
      }
    }
  }
}

async function validateScreenshot() {
  if (!existsSync(APP_THEME.screenshot)) {
    addIssue(`${APP_THEME.screenshot}: file not found`)
    return
  }

  try {
    const sharp = (await import('sharp')).default
    const meta = await sharp(APP_THEME.screenshot).metadata()
    const width = Number(meta.width)
    const height = Number(meta.height)
    if (!width || !height) {
      addIssue(`${APP_THEME.screenshot}: cannot read image dimensions`)
      return
    }

    if (width !== 512 || height !== 288) {
      addIssue(`${APP_THEME.screenshot}: expected 512x288, got ${width}x${height}`)
    }
  } catch (error) {
    addIssue(`${APP_THEME.screenshot}: failed to inspect image (${error.message})`)
  }
}

async function run() {
  validateSnippetFiles()
  validateAppThemeFiles()
  await validateScreenshot()

  if (issues.length > 0) {
    console.error('[FAIL] Obsidian theme audit found issues:')
    for (const issue of issues) {
      console.error(`  - ${issue}`)
    }
    process.exit(1)
  }

  console.log('[PASS] Obsidian theme audit passed.')
}

await run()
