import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { generateThemeVariants } from './generate-theme-variants.mjs'
import { generateSiteAssets } from './generate-site-assets.mjs'
import { generateObsidianThemes } from './generate-obsidian-themes.mjs'
import { generateObsidianAppTheme } from './generate-obsidian-app-theme.mjs'
import { generateColorLanguageReport } from './generate-color-language-report.mjs'
import { getThemeOutputFiles } from './color-system.mjs'

// 0. 从 color-system 源生成四个主题 JSON 变体（themes/ 仅作为产物）
generateThemeVariants()

// 1. 同步 JSON 到 public 和 extension
const src = 'themes'
const targets = ['public/themes', 'extension/themes']
const THEME_FILES = getThemeOutputFiles()

for (const target of targets) {
    mkdirSync(target, { recursive: true })
    for (const file of readdirSync(src)) {
        if (!file.endsWith('.json')) continue
        copyFileSync(join(src, file), join(target, file))
        console.log(`✓ ${src}/${file} → ${target}/${file}`)
    }
}

// 2. 从 JSON 提取 token 颜色，生成 src/data/tokens.ts
const themes = Object.fromEntries(
    Object.entries(THEME_FILES).map(([id, path]) => [id, JSON.parse(readFileSync(path, 'utf8'))])
)

function getToken(theme, scopes) {
    for (const scope of scopes) {
        const hit = theme.tokenColors.find(t =>
            Array.isArray(t.scope)
                ? t.scope.includes(scope)
                : t.scope === scope
        )
        if (hit) return hit.settings.foreground
    }
    return null
}

function buildTokenSet(theme) {
    return {
        bg: theme.colors['editor.background'],
        fg: theme.colors['editor.foreground'],
        lineBg: theme.colors['editor.lineHighlightBackground'],
        lineNo: theme.colors['editorLineNumber.foreground'],
        status: theme.colors['statusBar.background'],
        sidebar: theme.colors['sideBar.background'],
        border: theme.colors['sideBar.border'],
        keyword: getToken(theme, ['keyword']),
        fn: getToken(theme, ['entity.name.function']),
        method: getToken(theme, [
            'meta.function-call entity.name.function',
            'meta.method-call entity.name.function',
            'meta.function-call.js entity.name.function.js',
            'meta.method-call.js entity.name.function.js',
            'meta.function-call.ts entity.name.function.ts',
            'meta.method-call.ts entity.name.function.ts',
            'meta.function-call.py entity.name.function.py',
            'meta.method-call.py entity.name.function.py',
        ]),
        property: getToken(theme, ['entity.name.function.member', 'variable.other.property', 'meta.property-name']),
        string: getToken(theme, ['string']),
        number: getToken(theme, ['constant.numeric']),
        type: getToken(theme, ['entity.name.type']),
        variable: getToken(theme, ['variable']),
        operator: getToken(theme, ['keyword.operator']),
        comment: getToken(theme, ['comment']),
    }
}

const tokens = Object.fromEntries(
    Object.entries(themes).map(([id, theme]) => [id, buildTokenSet(theme)])
)

mkdirSync('src/data', { recursive: true })
writeFileSync(
    'src/data/tokens.ts',
    `// Auto-generated by scripts/sync-themes.mjs - DO NOT EDIT\n` +
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const\n` +
    `export type TokenSet = typeof tokens.dark\n`
)
console.log('✓ src/data/tokens.ts generated')

// 3. 生成站点与文档派生产物（CSS vars / docs baseline / extension metadata）
generateSiteAssets()

// 4. 生成 Obsidian 主题产物（基于同一 token 语义）
generateObsidianThemes()

// 5. 生成 Obsidian 社区主题标准产物（manifest/theme.css/versions/screenshot）
await generateObsidianAppTheme()

// 6. 生成色彩语言一致性报告（供文档与 CI 产物使用）
generateColorLanguageReport()
