import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { generateThemeVariants } from './generate-theme-variants.mjs'
import { generateSiteAssets } from './generate-site-assets.mjs'

// 0. 以 Hearth Dark 为核心生成其他变体
generateThemeVariants()

// 1. 同步 JSON 到 public 和 extension
const src = 'themes'
const targets = ['public/themes', 'extension/themes']

for (const target of targets) {
    mkdirSync(target, { recursive: true })
    for (const file of readdirSync(src)) {
        if (!file.endsWith('.json')) continue
        copyFileSync(join(src, file), join(target, file))
        console.log(`✓ ${src}/${file} → ${target}/${file}`)
    }
}

// 2. 从 JSON 提取 token 颜色，生成 src/data/tokens.ts
const dark = JSON.parse(readFileSync('themes/hearth-dark.json', 'utf8'))
const darkSoft = JSON.parse(readFileSync('themes/hearth-dark-soft.json', 'utf8'))
const light = JSON.parse(readFileSync('themes/hearth-light.json', 'utf8'))
const lightSoft = JSON.parse(readFileSync('themes/hearth-light-soft.json', 'utf8'))

function getToken(theme, scopes) {
    for (const scope of scopes) {
        const hit = theme.tokenColors.find(t =>
            Array.isArray(t.scope)
                ? t.scope.includes(scope)
                : t.scope === scope
        )
        if (hit) return hit.settings.foreground
    }
    return null
}

const tokens = {
    dark: {
        bg: dark.colors['editor.background'],
        fg: dark.colors['editor.foreground'],
        lineBg: dark.colors['editor.lineHighlightBackground'],
        lineNo: dark.colors['editorLineNumber.foreground'],
        status: dark.colors['statusBar.background'],
        sidebar: dark.colors['sideBar.background'],
        border: dark.colors['sideBar.border'],
        keyword: getToken(dark, ['keyword']),
        fn: getToken(dark, ['entity.name.function']),
        string: getToken(dark, ['string']),
        number: getToken(dark, ['constant.numeric']),
        type: getToken(dark, ['entity.name.type']),
        variable: getToken(dark, ['variable']),
        operator: getToken(dark, ['keyword.operator']),
        comment: getToken(dark, ['comment']),
    },
    darkSoft: {
        bg: darkSoft.colors['editor.background'],
        fg: darkSoft.colors['editor.foreground'],
        lineBg: darkSoft.colors['editor.lineHighlightBackground'],
        lineNo: darkSoft.colors['editorLineNumber.foreground'],
        status: darkSoft.colors['statusBar.background'],
        sidebar: darkSoft.colors['sideBar.background'],
        border: darkSoft.colors['sideBar.border'],
        keyword: getToken(darkSoft, ['keyword']),
        fn: getToken(darkSoft, ['entity.name.function']),
        string: getToken(darkSoft, ['string']),
        number: getToken(darkSoft, ['constant.numeric']),
        type: getToken(darkSoft, ['entity.name.type']),
        variable: getToken(darkSoft, ['variable']),
        operator: getToken(darkSoft, ['keyword.operator']),
        comment: getToken(darkSoft, ['comment']),
    },
    light: {
        bg: light.colors['editor.background'],
        fg: light.colors['editor.foreground'],
        lineBg: light.colors['editor.lineHighlightBackground'],
        lineNo: light.colors['editorLineNumber.foreground'],
        status: light.colors['statusBar.background'],
        sidebar: light.colors['sideBar.background'],
        border: light.colors['sideBar.border'],
        keyword: getToken(light, ['keyword']),
        fn: getToken(light, ['entity.name.function']),
        string: getToken(light, ['string']),
        number: getToken(light, ['constant.numeric']),
        type: getToken(light, ['entity.name.type']),
        variable: getToken(light, ['variable']),
        operator: getToken(light, ['keyword.operator']),
        comment: getToken(light, ['comment']),
    },
    lightSoft: {
        bg: lightSoft.colors['editor.background'],
        fg: lightSoft.colors['editor.foreground'],
        lineBg: lightSoft.colors['editor.lineHighlightBackground'],
        lineNo: lightSoft.colors['editorLineNumber.foreground'],
        status: lightSoft.colors['statusBar.background'],
        sidebar: lightSoft.colors['sideBar.background'],
        border: lightSoft.colors['sideBar.border'],
        keyword: getToken(lightSoft, ['keyword']),
        fn: getToken(lightSoft, ['entity.name.function']),
        string: getToken(lightSoft, ['string']),
        number: getToken(lightSoft, ['constant.numeric']),
        type: getToken(lightSoft, ['entity.name.type']),
        variable: getToken(lightSoft, ['variable']),
        operator: getToken(lightSoft, ['keyword.operator']),
        comment: getToken(lightSoft, ['comment']),
    },
}

mkdirSync('src/data', { recursive: true })
writeFileSync(
    'src/data/tokens.ts',
    `// Auto-generated by scripts/sync-themes.mjs - DO NOT EDIT\n` +
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const\n` +
    `export type TokenSet = typeof tokens.dark\n`
)
console.log('✓ src/data/tokens.ts generated')

// 3. 生成站点与文档派生产物（CSS vars / docs baseline / extension metadata）
generateSiteAssets()
