// Auto-generated by scripts/generate-site-assets.mjs - DO NOT EDIT
export const productData = {
  "brand": {
    "id": "vesper",
    "name": "Vesper",
    "displayName": "Vesper Color Languages",
    "summary": "A shared brand umbrella for distinct low-glare code color-language flavors."
  },
  "product": {
    "id": "hearthcode",
    "name": "HearthCode",
    "displayName": "HearthCode Theme",
    "summary": "Warm-neutral color language distributed across editors, reading surfaces, and the website.",
    "author": {
      "name": "HearthCode",
      "url": "https://theme.hearthcode.dev"
    },
    "wordmark": {
      "full": "HearthCode",
      "primary": "Hearth",
      "secondary": "Code"
    }
  },
  "scheme": {
    "id": "hearth",
    "name": "HearthCode",
    "headline": "Warm-neutral code color language"
  },
  "flavors": [
    {
      "id": "hearth",
      "name": "HearthCode",
      "shortName": "Hearth",
      "wordmark": {
        "full": "HearthCode",
        "primary": "Hearth",
        "secondary": "Code"
      },
      "headline": "Warm-neutral code color language",
      "summary": "A warm, low-glare color philosophy for code interfaces and reading surfaces.",
      "defaultVariant": "dark",
      "isDefault": true,
      "isActive": true,
      "isPublished": true
    },
    {
      "id": "cairn",
      "name": "CairnCode",
      "shortName": "Cairn",
      "wordmark": {
        "full": "CairnCode",
        "primary": "Cairn",
        "secondary": "Code"
      },
      "headline": "Stone-neutral code color language",
      "summary": "A grounded, low-glare color philosophy for code interfaces and reading surfaces.",
      "defaultVariant": "dark",
      "isDefault": false,
      "isActive": false,
      "isPublished": false
    }
  ],
  "site": {
    "titleSuffix": "HearthCode",
    "titleDescriptor": "Color Language for Code Interfaces",
    "defaultTitle": "HearthCode — Color Language for Code Interfaces",
    "authorName": "HearthCode",
    "metaPrefix": "hearthcode",
    "hostLabel": "theme.hearthcode.dev",
    "ogImagePath": "/og-hearth.png",
    "ogImageAlt": "HearthCode Theme preview",
    "wordmark": {
      "full": "HearthCode",
      "primary": "Hearth",
      "secondary": "Code"
    }
  },
  "release": {
    "version": "1.1.4"
  },
  "extension": {
    "itemName": "hearth-code.hearth-theme",
    "previewThemeLabel": "Hearth Dark",
    "themeCatalog": [
      {
        "variantId": "dark",
        "schemeId": "hearth",
        "flavorLabel": "Hearth",
        "climateLabel": "Dark",
        "label": "Hearth Dark",
        "uiTheme": "vs-dark",
        "path": "./themes/hearth-dark.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "darkSoft",
        "schemeId": "hearth",
        "flavorLabel": "Hearth",
        "climateLabel": "Dark Soft",
        "label": "Hearth Dark Soft",
        "uiTheme": "vs-dark",
        "path": "./themes/hearth-dark-soft.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "light",
        "schemeId": "hearth",
        "flavorLabel": "Hearth",
        "climateLabel": "Light",
        "label": "Hearth Light",
        "uiTheme": "vs",
        "path": "./themes/hearth-light.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "lightSoft",
        "schemeId": "hearth",
        "flavorLabel": "Hearth",
        "climateLabel": "Light Soft",
        "label": "Hearth Light Soft",
        "uiTheme": "vs",
        "path": "./themes/hearth-light-soft.json",
        "isActiveFlavor": true,
        "isDefaultFlavor": true,
        "isPublishedFlavor": true
      },
      {
        "variantId": "dark",
        "schemeId": "cairn",
        "flavorLabel": "Cairn",
        "climateLabel": "Dark",
        "label": "Cairn Dark",
        "uiTheme": "vs-dark",
        "path": "./themes/cairn-dark.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": false
      },
      {
        "variantId": "darkSoft",
        "schemeId": "cairn",
        "flavorLabel": "Cairn",
        "climateLabel": "Dark Soft",
        "label": "Cairn Dark Soft",
        "uiTheme": "vs-dark",
        "path": "./themes/cairn-dark-soft.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": false
      },
      {
        "variantId": "light",
        "schemeId": "cairn",
        "flavorLabel": "Cairn",
        "climateLabel": "Light",
        "label": "Cairn Light",
        "uiTheme": "vs",
        "path": "./themes/cairn-light.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": false
      },
      {
        "variantId": "lightSoft",
        "schemeId": "cairn",
        "flavorLabel": "Cairn",
        "climateLabel": "Light Soft",
        "label": "Cairn Light Soft",
        "uiTheme": "vs",
        "path": "./themes/cairn-light-soft.json",
        "isActiveFlavor": false,
        "isDefaultFlavor": false,
        "isPublishedFlavor": false
      }
    ]
  },
  "links": {
    "websiteUrl": "https://theme.hearthcode.dev",
    "marketplaceUrl": "https://marketplace.visualstudio.com/items?itemName=hearth-code.hearth-theme",
    "openVsxUrl": "https://open-vsx.org/extension/hearth-code/hearth-theme",
    "vscodeDevUrl": "https://vscode.dev/theme/hearth-code.hearth-theme/Hearth%20Dark",
    "repositoryUrl": "https://github.com/hearth-code/HearthTheme",
    "issuesUrl": "https://github.com/hearth-code/HearthTheme/issues",
    "releasesUrl": "https://github.com/hearth-code/HearthTheme/releases",
    "changelogUrl": "https://github.com/hearth-code/HearthTheme/blob/main/extension/CHANGELOG.md",
    "licenseUrl": "https://github.com/hearth-code/HearthTheme/blob/main/LICENSE",
    "docsRootUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs",
    "repoBlobRootUrl": "https://github.com/hearth-code/HearthTheme/blob/main",
    "repoTreeRootUrl": "https://github.com/hearth-code/HearthTheme/tree/main",
    "philosophyUrl": "https://github.com/hearth-code/HearthTheme/blob/main/color-system/schemes/hearth/philosophy.md",
    "schemeUrl": "https://github.com/hearth-code/HearthTheme/blob/main/color-system/schemes/hearth/scheme.json",
    "specUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-spec.md",
    "baselineUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/theme-baseline.md",
    "tuningUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-system-tuning.md",
    "reportUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-report.md",
    "contractChecklistUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-contract-checklist.md",
    "contractReviewUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-contract-review.md",
    "sourceColorSystemUrl": "https://github.com/hearth-code/HearthTheme/tree/main/color-system",
    "docsEnUrl": "https://theme.hearthcode.dev/docs",
    "docsZhUrl": "https://theme.hearthcode.dev/zh/docs",
    "docsJaUrl": "https://theme.hearthcode.dev/ja/docs"
  }
} as const
