// Auto-generated by scripts/generate-site-assets.mjs - DO NOT EDIT
export const productData = {
  "product": {
    "id": "hearthcode",
    "name": "HearthCode",
    "displayName": "HearthCode Theme",
    "summary": "Warm-neutral color language distributed across editors, reading surfaces, and the website.",
    "author": {
      "name": "HearthCode",
      "url": "https://theme.hearthcode.dev"
    },
    "wordmark": {
      "full": "HearthCode",
      "primary": "Hearth",
      "secondary": "Code"
    }
  },
  "scheme": {
    "id": "hearth",
    "name": "HearthCode",
    "headline": "Warm-neutral code color language"
  },
  "site": {
    "titleSuffix": "HearthCode",
    "titleDescriptor": "Color Language for Code Interfaces",
    "defaultTitle": "HearthCode — Color Language for Code Interfaces",
    "authorName": "HearthCode",
    "metaPrefix": "hearthcode",
    "hostLabel": "theme.hearthcode.dev",
    "ogImagePath": "/og-hearth.png",
    "ogImageAlt": "HearthCode Theme preview",
    "wordmark": {
      "full": "HearthCode",
      "primary": "Hearth",
      "secondary": "Code"
    }
  },
  "release": {
    "version": "1.1.3"
  },
  "extension": {
    "itemName": "hearth-code.hearth-theme",
    "previewThemeLabel": "Hearth Dark"
  },
  "links": {
    "websiteUrl": "https://theme.hearthcode.dev",
    "marketplaceUrl": "https://marketplace.visualstudio.com/items?itemName=hearth-code.hearth-theme",
    "openVsxUrl": "https://open-vsx.org/extension/hearth-code/hearth-theme",
    "vscodeDevUrl": "https://vscode.dev/theme/hearth-code.hearth-theme/Hearth%20Dark",
    "repositoryUrl": "https://github.com/hearth-code/HearthTheme",
    "issuesUrl": "https://github.com/hearth-code/HearthTheme/issues",
    "releasesUrl": "https://github.com/hearth-code/HearthTheme/releases",
    "changelogUrl": "https://github.com/hearth-code/HearthTheme/blob/main/extension/CHANGELOG.md",
    "licenseUrl": "https://github.com/hearth-code/HearthTheme/blob/main/LICENSE",
    "docsRootUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs",
    "repoBlobRootUrl": "https://github.com/hearth-code/HearthTheme/blob/main",
    "repoTreeRootUrl": "https://github.com/hearth-code/HearthTheme/tree/main",
    "philosophyUrl": "https://github.com/hearth-code/HearthTheme/blob/main/color-system/schemes/hearth/philosophy.md",
    "schemeUrl": "https://github.com/hearth-code/HearthTheme/blob/main/color-system/schemes/hearth/scheme.json",
    "specUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-spec.md",
    "baselineUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/theme-baseline.md",
    "tuningUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-system-tuning.md",
    "reportUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-report.md",
    "contractChecklistUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-contract-checklist.md",
    "contractReviewUrl": "https://github.com/hearth-code/HearthTheme/blob/main/docs/color-language-contract-review.md",
    "sourceColorSystemUrl": "https://github.com/hearth-code/HearthTheme/tree/main/color-system",
    "docsEnUrl": "https://theme.hearthcode.dev/docs",
    "docsZhUrl": "https://theme.hearthcode.dev/zh/docs",
    "docsJaUrl": "https://theme.hearthcode.dev/ja/docs"
  }
} as const
