// Auto-generated by scripts/sync-themes.mjs - DO NOT EDIT
export const tokens = {
  "dark": {
    "bg": "#23201c",
    "fg": "#d3c9b8",
    "lineBg": "#2d2924",
    "lineNo": "#655c4f",
    "status": "#6f3f1d",
    "sidebar": "#1e1a16",
    "border": "#3a3328",
    "keyword": "#d36b4a",
    "fn": "#e3b368",
    "string": "#8fbd79",
    "number": "#d5865f",
    "type": "#5aa7b6",
    "variable": "#dfd5c7",
    "operator": "#8f846f",
    "comment": "#6b5f4d"
  },
  "darkSoft": {
    "bg": "#2a2723",
    "fg": "#d7cdbc",
    "lineBg": "#34302b",
    "lineNo": "#72685a",
    "status": "#6e4527",
    "sidebar": "#24201c",
    "border": "#423a2f",
    "keyword": "#d36b4a",
    "fn": "#e3b368",
    "string": "#8fbd79",
    "number": "#d5865f",
    "type": "#5aa7b6",
    "variable": "#dfd5c7",
    "operator": "#8f846f",
    "comment": "#6b5f4d"
  },
  "light": {
    "bg": "#efe6d8",
    "fg": "#2f210e",
    "lineBg": "#e7ddcc",
    "lineNo": "#b49d7b",
    "status": "#9d4b12",
    "sidebar": "#e3d7c0",
    "border": "#d2c2a5",
    "keyword": "#8f2f1b",
    "fn": "#6a4102",
    "string": "#2f6f2d",
    "number": "#b14f30",
    "type": "#0f6a73",
    "variable": "#3d3022",
    "operator": "#7a6d51",
    "comment": "#847257"
  }
} as const
export type TokenSet = typeof tokens.dark
